Chapter 1; Exercise 1-1; using unknown function name instead of printf; the program does not compile; the compiler cannot deduce and suggest the correct name for this function and produces an error 'undefined reference to amir'; the program exits with an error code of 1